#!/usr/bin/env python3
"""Regenerate the `## Skill Structure` tree inside this skill's SKILL.md.

The section between the two `<!-- Generated by Scripts -->` markers is owned by this
script: everything in between is replaced on every run, so never hand-edit it.

    python3 scripts/auto-generate-skill-structure.py           # rewrite SKILL.md
    python3 scripts/auto-generate-skill-structure.py --check    # exit 1 if stale (CI / pre-commit)

Run it after adding or removing any reference or script, so the skill's own inventory
cannot drift from the files on disk. Line counts are included because they are the
loading cost a reader is choosing between.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

MARKER = "<!-- Generated by Scripts -->"
# Junk that must never appear in the tree: macOS metadata, bytecode, VCS internals.
SKIP_NAMES = {".DS_Store", "__pycache__", ".git", ".idea", ".vscode"}
SKIP_SUFFIXES = {".pyc", ".pyo"}
# Files rendered before directories at each level; the entry point first of all.
FIRST_FILES = ["SKILL.md", "README.md"]

TREE_HEADING_SUFFIX = "/"  # the heading is "<skill-dir-name>/", taken from the directory


def _default_skill_dir() -> Path:
    """The skill root = the parent of this script's directory (works from any cwd)."""
    return Path(__file__).resolve().parent.parent


def _keep(path: Path) -> bool:
    return path.name not in SKIP_NAMES and path.suffix not in SKIP_SUFFIXES


def _sort_key(path: Path) -> tuple:
    """Deterministic order: SKILL.md, README.md, other files, then directories."""
    if path.is_dir():
        return (1, path.name.lower())
    try:
        return (0, FIRST_FILES.index(path.name), "",)
    except ValueError:
        return (0, len(FIRST_FILES), path.name.lower())


def _line_count(path: Path, override: "dict[str, int] | None" = None) -> str:
    """Line count for text files. `override` supplies counts for files whose content is
    still being computed — SKILL.md itself, which contains this very tree."""
    if override and path.name in override:
        return f"  ({override[path.name]} lines)"
    if path.suffix.lower() in {".md", ".py", ".sh", ".txt", ".json", ".yaml", ".yml"}:
        try:
            n = sum(1 for _ in path.open("r", encoding="utf-8", errors="replace"))
        except OSError:
            return ""
        return f"  ({n} lines)"
    return ""


def _walk(directory: Path, prefix: str = "", override: "dict[str, int] | None" = None) -> list[str]:
    entries = sorted((p for p in directory.iterdir() if _keep(p)), key=_sort_key)
    lines: list[str] = []
    for index, entry in enumerate(entries):
        last = index == len(entries) - 1
        connector = "└── " if last else "├── "
        if entry.is_dir() and any(_keep(p) for p in entry.iterdir()):
            lines.append(f"{prefix}{connector}{entry.name}/")
            lines.extend(_walk(entry, prefix + ("    " if last else "│   "), override))
        elif entry.is_file():
            lines.append(f"{prefix}{connector}{entry.name}{_line_count(entry, override)}")
    return lines


def render(skill_dir: Path, override: "dict[str, int] | None" = None) -> str:
    """The full replacement block, markers included."""
    tree = [f"{skill_dir.name}{TREE_HEADING_SUFFIX}", *_walk(skill_dir, override=override)]
    body = "\n".join(tree)
    return f"{MARKER}\n\n```\n{body}\n```\n\n{MARKER}"


def splice(text: str, block: str) -> str:
    """Replace everything between the two markers with `block`."""
    first = text.find(MARKER)
    second = text.find(MARKER, first + len(MARKER)) if first != -1 else -1
    if first == -1 or second == -1:
        raise SystemExit(
            f"expected two {MARKER!r} markers to bracket the generated section"
        )
    return text[:first] + block + text[second + len(MARKER):]


def rewrite(skill_md: Path, *, check: bool) -> tuple[bool, str]:
    original = skill_md.read_text(encoding="utf-8")
    # The tree lists SKILL.md's own line count, so one pass is not a fixed point:
    # iterate until the block stops changing, then compare against what was on disk.
    candidate = original
    for _ in range(10):
        override = {skill_md.name: len(candidate.splitlines())}
        updated = splice(candidate, render(skill_md.parent, override))
        if updated == candidate:
            break
        candidate = updated
    if candidate == original:
        return False, "already up to date"
    if not check:
        skill_md.write_text(candidate, encoding="utf-8")
    return True, "rewritten" if not check else "stale"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the generated 'Skill Structure' section of SKILL.md.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--skill-dir",
        default=str(_default_skill_dir()),
        help="Skill root containing SKILL.md",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 when the section is stale",
    )
    args = parser.parse_args()

    skill_dir = Path(args.skill_dir).expanduser().resolve()
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.is_file():
        raise SystemExit(f"no SKILL.md under {skill_dir}")

    changed, status = rewrite(skill_md, check=args.check)
    print(f"{skill_md}: {status}")
    return 1 if (args.check and changed) else 0


if __name__ == "__main__":
    sys.exit(main())
