#!/usr/bin/env python3
"""Regenerate the `## Skill Structure` tree inside every SKILL.md of this repo.

One copy of this script lives here, at the repo root, not inside each skill: it walks the
skills root and rewrites the generated section of every SKILL.md that carries the two
`<!-- Generated by Scripts -->` markers, so a single run re-inventories the whole repo.
The section between the markers is owned by this script — everything in between is
replaced on every run, so never hand-edit it.

    python3 scripts/auto-generate-skill-structure.py                 # every skill
    python3 scripts/auto-generate-skill-structure.py --check          # exit 1 if any is stale
    python3 scripts/auto-generate-skill-structure.py manage-hermes-skills   # only these

Run it after adding, renaming or deleting any reference or script, so a skill's own
inventory cannot drift from the files on disk. Line counts are included because they are
the loading cost a reader is choosing between. A SKILL.md that is still an empty
placeholder, or that has no markers, is reported and left alone — never written into.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

MARKER = "<!-- Generated by Scripts -->"
# Junk that must never appear in the tree: macOS metadata, bytecode, VCS internals.
SKIP_NAMES = {".DS_Store", "__pycache__", ".git", ".idea", ".vscode"}
SKIP_SUFFIXES = {".pyc", ".pyo"}
# Files rendered before directories at each level; the entry point first of all.
FIRST_FILES = ["SKILL.md", "README.md"]

TREE_HEADING_SUFFIX = "/"  # the heading is "<skill-dir-name>/", taken from the directory


def _repo_root() -> Path:
    """The repo root = the parent of this script's directory (works from any cwd)."""
    return Path(__file__).resolve().parent.parent


def _default_skills_root() -> Path:
    return _repo_root() / "skills"


def _keep(path: Path) -> bool:
    return path.name not in SKIP_NAMES and path.suffix not in SKIP_SUFFIXES


def _sort_key(path: Path) -> tuple:
    """Deterministic order: SKILL.md, README.md, other files, then directories."""
    if path.is_dir():
        return (1, path.name.lower())
    try:
        return (0, FIRST_FILES.index(path.name), "",)
    except ValueError:
        return (0, len(FIRST_FILES), path.name.lower())


def _line_count(path: Path, override: "dict[str, int] | None" = None) -> str:
    """Line count for text files. `override` supplies counts for files whose content is
    still being computed — SKILL.md itself, which contains this very tree."""
    if override and path.name in override:
        return f"  ({override[path.name]} lines)"
    if path.suffix.lower() in {".md", ".py", ".sh", ".txt", ".json", ".yaml", ".yml"}:
        try:
            n = sum(1 for _ in path.open("r", encoding="utf-8", errors="replace"))
        except OSError:
            return ""
        return f"  ({n} lines)"
    return ""


def _walk(directory: Path, prefix: str = "", override: "dict[str, int] | None" = None) -> list[str]:
    entries = sorted((p for p in directory.iterdir() if _keep(p)), key=_sort_key)
    lines: list[str] = []
    for index, entry in enumerate(entries):
        last = index == len(entries) - 1
        connector = "└── " if last else "├── "
        if entry.is_dir() and any(_keep(p) for p in entry.iterdir()):
            lines.append(f"{prefix}{connector}{entry.name}/")
            lines.extend(_walk(entry, prefix + ("    " if last else "│   "), override))
        elif entry.is_file():
            lines.append(f"{prefix}{connector}{entry.name}{_line_count(entry, override)}")
    return lines


def render(skill_dir: Path, override: "dict[str, int] | None" = None) -> str:
    """The full replacement block, markers included."""
    tree = [f"{skill_dir.name}{TREE_HEADING_SUFFIX}", *_walk(skill_dir, override=override)]
    body = "\n".join(tree)
    return f"{MARKER}\n\n```\n{body}\n```\n\n{MARKER}"


def splice(text: str, block: str) -> str:
    """Replace everything between the two markers with `block`."""
    first = text.find(MARKER)
    second = text.find(MARKER, first + len(MARKER)) if first != -1 else -1
    if first == -1 or second == -1:
        raise ValueError(
            f"expected two {MARKER!r} markers to bracket the generated section"
        )
    return text[:first] + block + text[second + len(MARKER):]


def _shown(path: Path, repo_root: Path) -> Path:
    """Print paths relative to the repo root so a run can be read and diffed at a glance."""
    return path.relative_to(repo_root) if path.is_relative_to(repo_root) else path


def rewrite(skill_md: Path, *, check: bool) -> tuple[str, str]:
    """Regenerate one SKILL.md. Returns (state, status word), state being one of
    `changed` / `clean` / `no-section` / `placeholder`."""
    original = skill_md.read_text(encoding="utf-8")
    if not original.strip():
        return "placeholder", "skipped (empty placeholder)"
    if original.count(MARKER) < 2:
        return "no-section", f"skipped (no {MARKER} markers to fill)"
    # The tree lists SKILL.md's own line count, so one pass is not a fixed point:
    # iterate until the block stops changing, then compare against what was on disk.
    candidate = original
    for _ in range(10):
        override = {skill_md.name: len(candidate.splitlines())}
        updated = splice(candidate, render(skill_md.parent, override))
        if updated == candidate:
            break
        candidate = updated
    if candidate == original:
        return "clean", "already up to date"
    if not check:
        skill_md.write_text(candidate, encoding="utf-8")
    return "changed", "rewritten" if not check else "stale"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the generated 'Skill Structure' section of every SKILL.md under the skills root.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "skills",
        nargs="*",
        help="Skill directory names to limit the run to; with none, every skill is processed",
    )
    parser.add_argument(
        "--skills-root",
        default=str(_default_skills_root()),
        help="Directory whose immediate subdirectories are the skills",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 when any section is stale or missing",
    )
    args = parser.parse_args()

    skills_root = Path(args.skills_root).expanduser().resolve()
    if not skills_root.is_dir():
        raise SystemExit(f"no skills root directory at {skills_root}")

    wanted = args.skills
    names = sorted(
        d.name for d in skills_root.iterdir() if d.is_dir() and not d.name.startswith(".")
    )
    if wanted:
        unknown = [n for n in wanted if n not in names]
        if unknown:
            raise SystemExit(
                f"no such skill under {skills_root}: {', '.join(unknown)}\n"
                f"available: {', '.join(names)}"
            )
        names = [n for n in names if n in wanted]

    repo_root = _repo_root()
    counts = {"changed": 0, "clean": 0, "no-section": 0, "placeholder": 0, "no-skill-md": 0}
    for name in names:
        skill_dir = skills_root / name
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            print(f"{_shown(skill_dir, repo_root)}: skipped (no SKILL.md)")
            counts["no-skill-md"] += 1
            continue
        state, status = rewrite(skill_md, check=args.check)
        counts[state] += 1
        print(f"{_shown(skill_md, repo_root)}: {status}")

    summary = [
        f"{counts['changed']} {'stale' if args.check else 'rewritten'}",
        f"{counts['clean']} up to date",
    ]
    if counts["no-section"]:
        summary.append(f"{counts['no-section']} without a generated section")
    if counts["placeholder"]:
        summary.append(f"{counts['placeholder']} empty placeholder")
    if counts["no-skill-md"]:
        summary.append(f"{counts['no-skill-md']} without a SKILL.md")
    print(f"{len(names)} skills: {', '.join(summary)}")
    # A skill that is still a placeholder, or has no SKILL.md, is work in progress rather
    # than drift; a non-empty SKILL.md with no markers is drift, so --check fails on it.
    return 1 if (args.check and (counts["changed"] or counts["no-section"])) else 0


if __name__ == "__main__":
    sys.exit(main())
