#!/usr/bin/env python3
"""Verify a skill package: generated tree vs disk, and dangling pointers.

    python3 scripts/verify-skill-package.py skills/<name>
    python3 scripts/verify-skill-package.py skills/<name> --skills-root skills

The two checks that would otherwise be hand-typed greps, in one stdlib-only command so any
interpreter can run it with no dependencies:

1. **tree vs disk** — inside the `<!-- Generated by Scripts -->` block, every entry carrying
   `(N lines)` must match `len(path.read_text().splitlines())`, and the tree heading must equal the
   directory name. The block is generated, so a mismatch is a generator bug: re-run
   `scripts/auto-generate-skill-structure.py`, never hand-edit the block.
2. **pointers** — every `references/<name>.md` mentioned in `SKILL.md` or in a reference must exist
   either in this package or in a sibling skill under the skills root, because that is how one
   skill in this pack points at another (`maintain-hermes-skills` → `references/…`). A pointer
   resolving nowhere fails the check on purpose, and so does an illustration that is shaped like a
   pointer but names no real file — write those as shapes (`references/<topic>.md`). Text inside
   ``` fences is ignored, because a verbatim receipt may legitimately name a file that is not ours.

Exit status: 0 clean, 1 any problem, 2 no SKILL.md in the given directory.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

MARKER = "<!-- Generated by Scripts -->"
FENCE = re.compile(r"```.*?```", re.S)
ENTRY = re.compile(r"^([\u2502 ]*)([\u251c\u2514]\u2500\u2500 )(.*)$")
COUNT = re.compile(r"\((\d+) lines\)")
LOCAL_POINTER = re.compile(r"references/[A-Za-z0-9._-]+\.md")


def strip_fences(text: str) -> str:
    """Drop fenced blocks: a quoted receipt may name files that are not ours."""
    return FENCE.sub("", text)


def check_tree(root: pathlib.Path) -> list[str]:
    text = (root / "SKILL.md").read_text(encoding="utf-8")
    if not text.strip():
        # A WIP skeleton, not drift: same classification as the generator, so a gate that
        # would fail on the pack's placeholder never gets turned off.
        return []
    parts = text.split(MARKER)
    if len(parts) < 3:
        return ["no generated section: SKILL.md carries fewer than two markers"]
    lines = [l for l in parts[1].splitlines() if l.strip() and l.strip() != "```"]
    if not lines:
        return ["generated section is empty"]
    problems: list[str] = []
    heading = lines[0].strip()
    if heading != root.name + "/":
        problems.append(f"tree heading {heading!r} != directory name {root.name + '/'!r}")
    stack: list[str] = []
    for line in lines[1:]:
        match = ENTRY.match(line)
        if not match:
            continue
        depth = len(match.group(1)) // 4
        raw = match.group(3)
        is_dir = raw.endswith("/")
        count = COUNT.search(raw)
        name = COUNT.sub("", raw).strip().rstrip("/")
        stack = stack[:depth] + [name]
        if is_dir:
            continue
        path = root.joinpath(*stack)
        if not path.is_file():
            problems.append(f"tree names a missing file: {path.relative_to(root)}")
            continue
        if count:
            real = len(path.read_text(encoding="utf-8", errors="replace").splitlines())
            if int(count.group(1)) != real:
                problems.append(
                    f"{path.relative_to(root)}: tree says {count.group(1)} lines, disk has {real}"
                )
    return problems


def _siblings(root: pathlib.Path, skills_root: pathlib.Path) -> list[pathlib.Path]:
    if not skills_root.is_dir():
        return []
    return sorted(
        d for d in skills_root.iterdir() if d.is_dir() and not d.name.startswith(".") and d != root
    )


def check_pointers(
    root: pathlib.Path, skills_root: pathlib.Path, allowed: set[str]
) -> tuple[list[str], int, int, int]:
    """Returns (problems, local pointers, pointers in a sibling, declared exemptions)."""
    problems: list[str] = []
    local = cross = exempt = 0
    siblings = _siblings(root, skills_root)
    targets = [root / "SKILL.md"] + sorted((root / "references").glob("*.md"))
    for target in targets:
        if not target.is_file():
            continue
        body = strip_fences(target.read_text(encoding="utf-8"))
        for pointer in sorted(set(LOCAL_POINTER.findall(body))):
            if pointer in allowed:
                exempt += 1
                continue
            if (root / pointer).is_file():
                local += 1
                continue
            owner = next((d for d in siblings if (d / pointer).is_file()), None)
            if owner is not None:
                cross += 1
                continue
            where = target.relative_to(root) if target != root / "SKILL.md" else "SKILL.md"
            problems.append(f"{where} -> {pointer} does not exist in this package or a sibling skill")
    return problems, local, cross, exempt


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify a skill package: generated tree counts vs disk, and dangling pointers.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("skill_dir", help="Path to the skill directory (the one holding SKILL.md)")
    parser.add_argument(
        "--skills-root",
        default=None,
        help="Directory of sibling skills a cross-skill pointer may resolve in (default: the parent of skill_dir)",
    )
    parser.add_argument(
        "--allow-pointer",
        action="append",
        default=[],
        metavar="references/x.md",
        help="Declare a name that is evidence (a measured fixture, an illustration) rather than a pointer; "
        "repeatable, and each declaration is printed rather than silently skipped",
    )
    args = parser.parse_args()

    root = pathlib.Path(args.skill_dir).expanduser().resolve()
    if not (root / "SKILL.md").is_file():
        print(f"no SKILL.md in {root}")
        return 2
    skills_root = (
        pathlib.Path(args.skills_root).expanduser().resolve() if args.skills_root else root.parent
    )

    failed = False
    tree_problems = check_tree(root)
    pointer_problems, local, cross, exempt = check_pointers(root, skills_root, set(args.allow_pointer))
    for title, problems, summary in (
        ("tree vs disk", tree_problems, "tree vs disk: ok"),
        ("pointers", pointer_problems, f"pointers: ok ({local} local, {cross} in sibling skills)"),
    ):
        if problems:
            failed = True
            print(f"{title}: {len(problems)} problem(s)")
            for problem in problems:
                print(f"  - {problem}")
        else:
            print(summary)
    if exempt:
        print(f"pointers: {exempt} declared exemption(s) not counted: {', '.join(sorted(set(args.allow_pointer)))}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
